### ISSUE TITLE
GUI not loading

### ISSUE THREAD

**Issue by biglawinvestor** [versionpress/support#166]
Hi -

The GUI is not loading per this screenshot: https://cl.ly/040d28dde878

When I debug with the console I see these error message: https://cl.ly/5d26cd9584e1

Clicking the commit link gets me a 403 error, as seen here: https://cl.ly/649c6bd4367f

The network errors are shown here: https://cl.ly/8f01d1a0c19e

And my host is telling me this is the error message they see:

[03-May-2019 14:27:16 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getDescription() on null in /home/nginx/domains/gamma.biglawinvestor.com/public/wp-content/plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php:108
Stack trace:
#0 /home/nginx/domains/gamma.biglawinvestor.com/public/wp-content/plugins/versionpress/src/ChangeInfos/ChangeInfoEnvelope.php(81): VersionPress\ChangeInfos\TrackedChangeInfo->getChangeDescription()
#1 /home/nginx/domains/gamma.biglawinvestor.com/public/wp-content/plugins/versionpress/src/Api/VersionPressApi.php(262): VersionPress\ChangeInfos\ChangeInfoEnvelope->getChangeDescription()
#2 /home/nginx/domains/gamma.biglawinvestor.com/public/wp-content/plugins/versionpress/src/Api/VersionPressApi.php(188): VersionPress\Api\VersionPressApi->getCommits(Object(WP_REST_Request))
#3 /home/nginx/domains/gamma.biglawinvestor.com/public/wp-includes/rest-api/class-wp-rest-server.php(946): VersionPress\Api\VersionPressApi->VersionPress\Api\{closure}(Object(WP_REST_Request))
#4 /home/nginx/domains/gamma.biglawinvestor. in /home/nginx/domains/gamma.biglawinvestor.com/public/wp-content/plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php on line 108

- VersionPress version: 5.1.1
- WordPress version: Version 4.0-beta2
- OS, webserver, PHP: nginx
- Git version: 2.16.5

Does anyone have any ideas on what I might do next to troubleshoot? I have all plugins deactivated on my staging site currently.

**Comment by pavelevap** [comment]
Hi, @biglawinvestor,

is your staging site cloned by VersionPress from original (production) site?
Did you tried to merge some changes production/staging?
Which PHP version do you use on this server (current reports were mostly related to 5.6)?

Could you try to inspect current `.git` repo (created by VersionPress) and search for strange commits (especially based on your merge operations)? Maybe there is missing commit message or something else which could help us to identify real cause of this issue.

Similar (not resolved) issue: #84

**Comment by biglawinvestor** [comment]
Hi @pavelevap!

Thanks for such a quick response. I'm running PHP version 7.2.13. The staging site was not cloned by VersionPress. The staging site was set up separately and then I installed VersionPress. Now that I'm thinking about it, I did get a timeout error during installation (there are a lot of posts and comments on my site) but then when I returned to Wordpress, after a long wait of showing maintenance mode, VersionPress showed as installed.

I am going to try and reinstall VersionPress per your suggestion in the other thread. I will also see if I can find any missing commits in the .git repo.

**Comment by biglawinvestor** [comment]
Wow. It looks like reinstalling it worked: https://cl.ly/eaaf189ae173

**Comment by pavelevap** [comment]
Great, could you please see your PHP `error_log` to check if there is any particular error related to this issue? Did you find any particular problems within VP `.git` repo? I am not sure how exactly timeout is handled, but VP should not be "installed" until everything is really ready. Or could you share your damaged repo from `wp-content/vpbackups` so we could find the real cause?
